# Generated by Django 5.0.6 on 2024-06-23 00:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('descripción', models.CharField(max_length=50)),
                ('precio', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)])),
                ('foto', models.ImageField(upload_to='producto')),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarjeta_de_credito', models.IntegerField(verbose_name='numero tarjeta')),
                ('fecha_de_vencimiento', models.CharField(max_length=50, verbose_name='fecha vencimiento')),
                ('codigo_de_seguridad', models.IntegerField(verbose_name='cv')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('run', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='rut')),
                ('correo', models.EmailField(max_length=150, unique=True, verbose_name='correo')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='apellido')),
                ('telefono', models.IntegerField(verbose_name='teléfono')),
                ('comuna', models.CharField(max_length=50, verbose_name='comuna')),
                ('direccion', models.CharField(max_length=50, verbose_name='direccion')),
                ('is_staff', models.BooleanField(default=False, verbose_name='empleado')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='superuser')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_web.tarjeta', verbose_name='tarjeta')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
