# Generated by Django 5.0.6 on 2024-06-23 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='run',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='rut'),
        ),
    ]
