# Generated by Django 5.0.6 on 2024-06-23 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_web', '0005_alter_tarjeta_tarjeta_de_credito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='tarjeta',
        ),
    ]
