# Generated by Django 5.0.6 on 2024-06-24 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_web', '0006_remove_usuario_tarjeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='tarjeta_de_credito',
            field=models.IntegerField(unique=True, verbose_name='numero tarjeta'),
        ),
    ]
