# Generated by Django 5.0.6 on 2024-06-25 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_web', '0008_tarjeta_uusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto_carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='cantidad')),
                ('subtotal', models.IntegerField(verbose_name='subtotal')),
                ('producto_c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_web.producto', verbose_name='producto_c')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
        ),
    ]
