# Generated by Django 5.0.6 on 2024-06-25 03:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_web', '0009_producto_carro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto_carro',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='producto_carro',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='producto_carro',
            name='cantidad',
            field=models.IntegerField(default=1, verbose_name='cantidad'),
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='producto_carro',
            name='carrito',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mi_web.carrito'),
        ),
    ]
