# Generated by Django 5.0.6 on 2024-06-26 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_web', '0011_alter_producto_carro_carrito'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarritoDeCompras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='producto_carro',
            name='carrito',
        ),
        migrations.RemoveField(
            model_name='producto_carro',
            name='producto_c',
        ),
        migrations.CreateModel(
            name='ItemCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_web.carritodecompras')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_web.producto')),
            ],
        ),
        migrations.AddField(
            model_name='carritodecompras',
            name='productos',
            field=models.ManyToManyField(through='mi_web.ItemCarrito', to='mi_web.producto'),
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
        migrations.DeleteModel(
            name='Producto_carro',
        ),
    ]
