# Generated by Django 5.0.6 on 2024-06-23 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_web', '0002_alter_usuario_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(max_length=10, verbose_name='telefono'),
        ),
    ]
