# Generated by Django 5.0.6 on 2024-06-23 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_web', '0003_alter_usuario_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(max_length=9, verbose_name='telefono'),
        ),
    ]
