# Generated by Django 5.0.6 on 2024-06-25 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_web', '0010_remove_producto_carro_subtotal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto_carro',
            name='carrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mi_web.carrito'),
        ),
    ]
