# Generated by Django 5.0.6 on 2024-06-26 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_web', '0014_alter_carritodecompras_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carritodecompras',
            name='user',
        ),
    ]
